<?php

/**
 * English stop words for search indexing
 *
 * A lean list of function words (articles, pronouns, prepositions, conjunctions,
 * auxiliary verbs) filtered out during indexing to improve search relevance and
 * reduce index size. These words are not indexed except in title fields.
 *
 * Deliberately excludes content-bearing words such as "need", "best", "good",
 * "back", "well", "new", "old", "get", "take", "use", "make", "way", "most",
 * "more", "less", "small", "large", "up", "down", "over", "under", "out",
 * "off", "again", "once", "only", "both", "each", "few", "all", "same",
 * "own", "just", "still", "after", "before", "between", "during", "against",
 * and "below" — BM25 IDF already discounts common words, and these carry
 * meaning worth indexing. Do not re-add them.
 */

return [
    'a',
    'about',
    'above',
    'am',
    'an',
    'and',
    'any',
    'are',
    'as',
    'at',
    'be',
    'because',
    'been',
    'being',
    'but',
    'by',
    'can',
    'could',
    'did',
    'do',
    'does',
    'doing',
    'else',
    'for',
    'from',
    'had',
    'has',
    'have',
    'having',
    'he',
    'her',
    'hers',
    'him',
    'his',
    'how',
    'i',
    'if',
    'in',
    'into',
    'is',
    'it',
    'its',
    'may',
    'me',
    'might',
    'mine',
    'must',
    'my',
    'no',
    'nor',
    'not',
    'of',
    'on',
    'or',
    'ought',
    'our',
    'ours',
    'per',
    'shall',
    'she',
    'should',
    'so',
    'some',
    'such',
    'than',
    'that',
    'the',
    'their',
    'theirs',
    'them',
    'then',
    'there',
    'these',
    'they',
    'this',
    'those',
    'through',
    'to',
    'too',
    'us',
    'very',
    'was',
    'we',
    'were',
    'what',
    'when',
    'where',
    'which',
    'while',
    'who',
    'whom',
    'why',
    'will',
    'with',
    'would',
    'you',
    'your',
    'yours',
];
